name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        run: npm install
      - name: Start Server
        run: npm start
      - name: Cypress run
        run: npx cypress run
