name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Cypress run
        run: npx cypress run

